# Static or shared libraries should be built (STATIC or SHARED)?
LibType := SHARED

# Select optimization (-O or -g). -O will be automatically bumped up to the 
# highest level of optimization the compiler supports. If want something in
# between then specify the exact level you want, e.g., -O1 or -O2
OptLevel := -O2
#OptLevel := -g

LIBNAME := Smi

LIBSRC := 
LIBSRC += SmiModel.cpp

##############################################################################
# You should not need to edit below this line.
##############################################################################
# The location of the customized Makefiles
include ${MakefileDir}/Makefile.coin
include ${MakefileDir}/Makefile.location
ifeq ($(OptLevel),-g)
#     CXXFLAGS += -DCGL_DEBUG
endif
#    CXXFLAGS += -DCGL_DEBUG

export ExtraIncDir  := ${SmiIncDir} ${OslSeIncDir} ${OsiIncDir} ${CoinIncDir} 
export ExtraLibDir  := ${SmiLibDir} ${OslSeLibDir} ${OsiLibDir} ${CoinLibDir}
export ExtraLibName := ${SmiLibName} ${OslSeLibName} ${OsiLibName} ${CoinLibName}
export ExtraDefine  := ${SmiDefine} ${OslSeDefine} ${OsiDefine} ${CoinDefine} 

export LibType OptLevel LIBNAME LIBSRC

###############################################################################

.DELETE_ON_ERROR:

.PHONY: default install library

default: install

install library :
	$(MAKE) -f ${MakefileDir}/Makefile.lib $@
